### ISSUE TITLE
可以用yescaptcha来获取获取arkose token吗？

### ISSUE THREAD

**Issue by weikecloud** [MagicalMadoka/openai-signup-bot#1]

**Comment by MagicalMadoka** [comment]
我也想用一个平台把这两个事情解决了。但是yes测试下来。1.打码时间长，2.打下来的token大概率用不了。

**Comment by weikecloud** [comment]
好，那我按照你的方式去测试一下，大佬辛苦了

**Comment by MagicalMadoka** [comment]
用之前 pull一下，刚才修了几个bug

**Comment by weikecloud** [comment]
ip2world 可以代替 okeyproxy 吗？

**Comment by MagicalMadoka** [comment]
只要他能符合 yes的格式要求就行。代理没啥限制。但是格式必须一致。

**Comment by weikecloud** [comment]
你是两个代理配置都用okeyproxy？

**Comment by MagicalMadoka** [comment]
代理都用一样的是可以的。只要格式ok。okeyproxy的格式是ok的。

注册成功会自动获取sess

格式是：
账号----密码----sess----rt

如果账号被授权了额度，会额外保存到另一个文件里面，readme有说明

**Comment by weikecloud** [comment]
感谢，已经注册成功了，但好像有一些会失败，这些会重新去验证么？

**Comment by weikecloud** [comment]
@MagicalMadoka 我感觉发送了几十个验证码都不成功一个，是咋回事呢？
