### ISSUE TITLE
请问这个错误是什么原因导致的

### ISSUE THREAD

**Issue by duansix** [MagicalMadoka/openai-signup-bot#5]
![QQ截图20240124134308](https://github.com/MagicalMadoka/openai-signup-bot/assets/75287966/ffc398b6-fcf0-4dca-b9b1-faf44c8c2777)
失败次数很高 只能成功几个

**Comment by duansix** [comment]
估计是ip质量的问题？

**Comment by duansix** [comment]
![Uploading QQ截图20240124155220.png…]()

**Comment by duansix** [comment]
![QQ截图20240124155220](https://github.com/MagicalMadoka/openai-signup-bot/assets/75287966/44daf55f-9517-443b-a826-b2f2856555b2)

**Comment by MagicalMadoka** [comment]
这个你要找yes老板看看，任务id发给他，看看是他的问题还是你的代理的问题

**Comment by weikecloud** [comment]
@MagicalMadoka 大佬，你的proxy是配置一个还是多个呢？
