### ISSUE TITLE
用了项目推荐的代理平台和其他代理平台，依然获取的都是'next': 'verify_email'

### ISSUE THREAD

**Issue by weikecloud** [MagicalMadoka/openai-signup-bot#7]
是不是哪里还要做认证呢？我尝试将ua，Cookie，proxy都保存下来并且每次请求都传入，还是这样，还有其他好的解决方案么？

**Comment by MagicalMadoka** [comment]
贴一下具体的日志，看你的描述是cf过不去？

**Comment by weikecloud** [comment]
![Uploading WX20240126-144112.png…]()

**Comment by weikecloud** [comment]
![WX20240126-144112](https://github.com/MagicalMadoka/openai-signup-bot/assets/36788191/b11641da-85bc-4ea1-a002-d694d4187a47)

**Comment by weikecloud** [comment]
给我感觉是CF过不去，就是明明已经将连接传过去给yes平台，还返回了全部内容，并且我用账号密码登录进去确实能到填写用户信息的界面，就是用协议一直都是返回verify_email，并不是返回register，我昨天用了一天时间去将整个okeyproxy代理池都试了一遍，然后用的是延时3分钟，不同的地区我都手动切换，还是一样

**Comment by weikecloud** [comment]
![image](https://github.com/MagicalMadoka/openai-signup-bot/assets/36788191/237e3782-5940-4253-8792-cf86f4cf1f53)
而且我还按照yescaptcha文档上面每次获取到这三个参数都保存到本地，然后在_login方法里面读取并且引用再发送过去也是一样，现在有点迷茫了~

**Comment by MagicalMadoka** [comment]
这是cf还没过去，yes过一次cf大概需要60～120s，所以在这个时间里面刷这个日志是正常的。具体时间可以去yes控制台看一下。如果yes那边显示过了。看一下他过的cookie里面有没有cf_clearance（PS，我最新的代码应该是有这个校验的）他没过也会重试的。至于ip、ua 本项目的场景不涉及，你不需要乱改。


另外你说的用账号密码登录进去这个场景应该是不存在的，我不太确定是否是因为你的浏览器cookie导致的。建议完全清除cookie再说。

**Comment by weikecloud** [comment]
我是用无痕迹浏览器去测试了一下一直没有返回register的账号，发现是能登录到新增用户信息的界面，而且我刚再试了一下是有过CF
![image](https://github.com/MagicalMadoka/openai-signup-bot/assets/36788191/14012f31-5749-41cc-af90-032d4970dc58)

**Comment by weikecloud** [comment]
![image](https://github.com/MagicalMadoka/openai-signup-bot/assets/36788191/417cb446-418f-49e4-b417-0c5ca0f57c94)

**Comment by weikecloud** [comment]
这是重新给yes那边做认证，然后内容是：Your email was verified but you are no longer authenticated. Please return to the device where you began sign up and refresh the page ，邮箱是已经认证了的！

**Comment by MagicalMadoka** [comment]
你先弄成单线程。再做测试，另外cf_clearance是让你去yes控好台看的，不是看登录的。

**Comment by MagicalMadoka** [comment]
用最新的代码，如果你乱改cookie完全可能出现你描述的场景。但是正常情况下应该没有这种情况

**Comment by weikecloud** [comment]
这是我单线程的
![image](https://github.com/MagicalMadoka/openai-signup-bot/assets/36788191/42e283d1-6918-4846-b190-0ddd524a1612)

**Comment by MagicalMadoka** [comment]
看里面的cf_clearance啊

**Comment by weikecloud** [comment]
![image](https://github.com/MagicalMadoka/openai-signup-bot/assets/36788191/79cfa0c7-92ba-4696-a70a-2e3694158620)
这个吗

**Comment by weikecloud** [comment]
我用你最新的代码重新跑了一下，也是都会有cf_clearance返回

**Comment by MagicalMadoka** [comment]
嗯，搞一个这样的账号密码过来

**Comment by weikecloud** [comment]
在这里发吗？还是TG？

**Comment by MagicalMadoka** [comment]
都可以

**Comment by weikecloud** [comment]
看看TG艾特你了

**Comment by MagicalMadoka** [comment]
此问题和yes无关，可能是不同的服务商对imap实现不同引起的，暂时先关闭，如果有新问题可以再开新的issue
